[package]
name = "tacp"
version = "0.0.0-beta1"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
bitflags = { version = "~2.13.2", default-features = false }
zerocopy = { version = "~0.8.59", default-features = false }
zerocopy-derive = { version = "~0.8.59", default-features = false }

[features]
default = ["obfuscation"]
obfuscation = []
expose_zerocopy = []

[lints.clippy]
len_without_is_empty = "allow"
too_many_arguments = "allow"
doc_markdown = "allow"
pedantic = "warn"
must_use_candidate = "allow"
nursery = "warn"
empty_enums = "allow" # upstream bug in zerocopy
