[workspace]
members = ["tacp", "tacpd", "test_client"]
resolver = "2"

[workspace.package]
authors = ["Andrew Piroli"]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 1

[profile.deboog]
inherits = "dev"
opt-level = 0

[profile.release]
lto = true
