[package]
name = "tserver"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tacp = { path = "../../tacp", features = ["obfuscation"] }
tokio = { version = "~1.52.3", default-features = false, features = ["net", "rt", "io-util", "time"] }
tracing = { version = "~0.1.44", default-features = false, features = ["attributes", "std", "tracing-attributes", "release_max_level_info"] }
tracing-subscriber = { version = "~0.3.23", default-features = false, features = ["ansi", "fmt", "std"] }
reqwest = { version = "~0.13.3", default-features = false, features = ["blocking", "json"] }
serde = { version = "~1.0.228", default-features = false, features = ["derive"] }
